[[mods]] #mandatory
    modId="buildinggadgets" #mandatory
    version="${version}" #mandatory
    displayName="Building Gadgets" #mandatory
    description='''Adds some gadgets to help you build!
    Building and Exchanging Gadget offer basic building & exchanging functionality for easily creating walls/columns etc.
    The Destruction Gadget will help you clear out large Areas for your complex builds which you can Copy and Paste at will with the Copy-Paste Gadget!
    '''
## A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.buildinggadgets]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[${forge_major},)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="BEFORE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
## We don't need to depend on the API, as it will always be in the same jar with an apropiate version, this way we can let forge decide the loading order
#[[dependencies.buildinggadgets]] #optional
    # the modid of the dependency
    #modId="buildinggadgets_api" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    #mandatory=true #mandatory
    # The version range of the dependency
    #versionRange="[${api_version},)" #mandatory
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    #side="BOTH"